name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Dear Contributor! Thank you for creating an issue. We will check it shortly and get back to you with feedback. Welcome to the Otasoft Community! ;)'
        pr-message: 'Dear Contributor! Thank you for creating a Pull Request. We will check it shortly and get back to you with feedback. Welcome to the Otasoft Community! ;)'
